server:
  port: 8080

spring:
  application:
    name: mymodulith
  datasource:
    url: jdbc:sqlite:./data/mymodulith.db
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.community.dialect.SQLiteDialect
  sql:
    init:
      mode: always

#  modulith:
#    republish-outstanding-events-on-restart: false

logging:
  level:
    org.springframework: ERROR
    org.springframework.modulith: DEBUG
    org.springframework.web: DEBUG